create table cinema.series (
  serie_id integer not null,
  serie text not null
);

alter table cinema.series
  alter column serie_id
  add generated by default as identity;

alter table cinema.series
  add primary key (serie_id);

\copy cinema.series from './041-series.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

create table cinema.films (
  film_id int not null,
  titre text not null,
  titre_original text,
  annee integer,
  sortie date,
  duree integer,
  serie integer,
  slogan text,
  pays text[]
);

alter table cinema.films
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

alter table cinema.films add
  constraint film_serie_fk foreign key (serie)
    references cinema.serie (id) match simple
    on update no action
    on delete no action
    not valid;

\copy cinema.films (film_id,titre,titre_original,annee,sortie,duree,franchise_id, pays) from './030-films.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

create table cinema.films_motscles (
  film_id int not null,
  motcle_id integer not null
);

create table cinema.motscles (
  motcle_id integer not null,
  motcle text not null
);

-- Genres

create table cinema.genres (
  genre_id integer not null,
  genre text not null
);

\copy cinema.genre from './041-genres.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

create table cinema.films_genres (
  film_id int not null,
  genre_id integer not null
);
