\connect iutsd;

drop table if exists cinema.film_genre;

create table if not exists cinema.film_genre
(
  film uuid not null,
  genre integer not null,
  constraint film_genre_pkey primary key (film, genre),
  constraint film_genre_film foreign key (film)
    references cinema.film (id) match simple
    on update no action
    on delete no action
    not valid,
  constraint film_genre_genre foreign key (genre)
    references cinema.genre (id) match simple
    on update no action
    on delete no action
    not valid
);

copy cinema.film_genre (film, genre)
  from '/tmp/41-film_genre.csv' delimiter ','
  csv header quote '"' escape ''''
  encoding 'utf8';

create table if not exists cinema.production
(
  id integer not null primary key generated by default as identity,
  film uuid not null,
  societe uuid not null,
   CONSTRAINT production_film_fk FOREIGN KEY (film)
        REFERENCES cinema.film (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
  CONSTRAINT production_societe_fk FOREIGN KEY (societe)
        REFERENCES cinema.societe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

copy cinema.production (film, societe)
  from '/tmp/41-production.csv' delimiter ','
  csv header quote '"' escape ''''
  encoding 'utf8';
