create schema if not exists cinema
  authorization iutsd;

alter default privileges
  for role postgres
  in schema cinema
  grant insert, select, update, delete on tables to iutsd;

-- Personnes

create table cinema.personnes (
  personne_id int not null,
  nom text,
  prenom text,
  naissance date,
  deces date,
  nationalite text,
  artiste text,
  popularite decimal default 0
);

alter table cinema.personnes
  add constraint personne_naissance
  check (naissance > '1730-01-01') not valid;

alter table cinema.personnes
  add constraint personne_deces
  check (deces > naissance) not valid;

alter table cinema.personnes
  add constraint personne_nationalite
  check (char_length(nationalite) = 2) not valid;

create unique index personnes_unique
  on cinema.personnes using btree (nom, prenom);

alter table cinema.personnes
  add constraint personnes_unique unique
  using index personnes_unique;

alter table cinema.personnes
  alter column personne_id
  add generated by default as identity;

create unique index personnes_pk
  on cinema.personnes
  using btree (personne_id);

alter table cinema.personnes
  add primary key using index personnes_pk;

alter table if exists cinema.personnes owner to iutsd;

alter table cinema.personnes
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

\copy cinema.personnes (personne_id, nom, prenom, naissance, deces, nationalite, artiste, popularite) from '010-personnes.csv' delimiter ',' csv header quote '"' encoding 'utf8';

-- Sociétés

create table cinema.societes (
  societe_id int not null,
  societe text not null,
  uei text
);

comment on column cinema.societes.uei is 'Unique Entity ID';

alter table cinema.societes
  alter column societe_id
  add generated by default as identity;

alter table cinema.societes
  add primary key (societe_id);

\copy cinema.societes from './011-societes.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';
