create table cinema.series (
  serie_id integer not null,
  serie text not null
);

alter table cinema.series
  alter column serie_id
  add generated by default as identity;

alter table cinema.series
  add primary key (serie_id);

\copy cinema.series from './041-series.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

create table cinema.films (
  film_id int not null,
  titre text not null,
  titre_original text,
  annee integer,
  sortie date,
  duree integer,
  serie_id integer,
  slogan text,
  pays text[]
);

alter table cinema.films
  alter column film_id
  add generated by default as identity;

alter table cinema.films
  add primary key (film_id);


alter table cinema.films
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

alter table cinema.films
  add foreign key (serie_id)
    references cinema.series match simple
    on update no action
    on delete no action
    not valid;

\copy cinema.films (film_id,titre,titre_original,annee,sortie,duree,serie_id, pays) from './030-films.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

create table cinema.films_motscles (
  film_id int not null,
  motcle_id integer not null
);

create table cinema.motscles (
  motcle_id integer not null,
  motcle text not null
);

alter table cinema.motscles
  add primary key (motcle_id);

create unique index film_motscles_pkey
  on cinema.films_motscles
  using btree (film_id, motcle_id);

alter table cinema.films_motscles
  add primary key
  using index film_motscles_pkey;

create index film_motscles_films
  on cinema.films_motscles
  using btree (film_id);

create index film_motscles_motscles
  on cinema.films_motscles
  using btree (motcle_id);

alter table cinema.films_motscles
  add foreign key (film_id)
  references cinema.films(film_id)
  on delete cascade;


alter table cinema.films_motscles
  add foreign key (motcle_id)
  references cinema.motscles(motcle_id)
  on delete cascade;

-- Genres

create table cinema.genres (
  genre_id integer not null,
  genre text not null
);

-- Clé primaire auto incrément

alter table cinema.genres
  alter column genre_id
  add generated by default as identity;

create unique index genres_pk
  on cinema.genres
  using btree (genre_id);

alter table cinema.genres
  add primary key using index genres_pk;

\copy cinema.genres from './041-genres.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';
