create table if not exists cinema.salles (
  salle_id integer not null,
  etablissement_id integer not null,
  salle text not null,
  sieges integer not null
);

alter table cinema.salles
  add primary key (salle_id);

alter table cinema.salles
  add foreign key (etablissement_id) references cinema.etablissements
  on delete cascade;

\copy cinema.salles (salle_id, etablissement_id, salle, sieges) from './043-salles.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

-- seances

create table if not exists cinema.seances (
  seance_id int not null,
  film_id int not null,
  salle_id int not null,
  seance date not null
);


alter table cinema.seances
  alter column seance_id
  add generated by default as identity;

create index on cinema.seances
  using btree (film_id);

create index on cinema.seances
  using btree (salle_id);

alter table cinema.seances
  add primary key (seance_id);

alter table cinema.seances
add foreign key (film_id) references cinema.films
  on delete cascade;

alter table cinema.seances
  add foreign key (salle_id) references cinema.salles;
