drop table if exists cinema.serie;

create table  if not exists cinema.serie (
  id integer not null primary key generated by default as identity,
  serie text not null
);

copy cinema.serie
  from '/tmp/41-serie.csv' delimiter ','
  csv header quote '"' escape ''''
  encoding 'utf8';


drop table if exists cinema.film;

create table cinema.film (
  id uuid default gen_random_uuid() not null,
  titre text not null,
  titre_original text,
  annee integer,
  sortie date,
  duree integer,
  serie integer,
  constraint film_pkey primary key (id)
);

alter table cinema.film
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

alter table cinema.film add
  CONSTRAINT film_serie_fk FOREIGN KEY (serie)
        REFERENCES cinema.serie (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

copy cinema.film (id,titre,titre_original,annee,sortie, duree,serie)
  from '/tmp/30-film.csv' delimiter ','
  csv header quote '"' escape ''''
  encoding 'utf8';
