

create table jardins.preparations (
  preparation_id bigint not null,
  jardin_id bigint not null,
  preparation text not null,
  jour smallint not null
);

alter table jardins.preparations
  alter column preparation_id
  add generated by default as identity;

alter table jardins.preparations
  add primary key (preparation_id);

create table jardins.calendriers (
  calendrier_id bigint not null,
  jardin_id bigint not null,
  calendrier text not null
);

alter table jardins.calendriers
  alter column calendrier_id
  add generated by default as identity;

alter table jardins.calendriers
  add foreign key (jardin_id) references jardins.jardins on delete cascade not valid;

alter table jardins.calendriers
  validate constraint calendriers_jardin_id_fkey;

alter table jardins.calendriers
  add primary key (calendrier_id);

create table jardins.tournees (
  tournee_id bigint not null,
  jardin_id bigint not null,
  tournee text,
  preparation_id bigint not null,
  calendrier_id bigint,
  ordre smallint,
  couleur text
);

alter table jardins.tournees
  add foreign key (jardin_id) references jardins.jardins;

alter table jardins.tournees
  add foreign key (preparation_id) references jardins.preparations;

alter table jardins.tournees
  add primary key (tournee_id);

alter table jardins.tournees
  add foreign key (calendrier_id) references jardins.calendriers not valid;

alter table jardins.tournees
  validate constraint tournees_calendrier_id_fkey;

alter table jardins.tournees alter column tournee_id add generated by default as identity;

create table jardins.distributions (
  distribution_id bigint not null,
  jardin_id bigint not null,
  tournee_id bigint not null,
  depot_id bigint,
  adherent_id bigint,
  ordre smallint
);

alter table jardins.distributions
  alter column distribution_id
  add generated by default as identity;

alter table jardins.distributions
  add primary key (distribution_id);

alter table jardins.distributions
  add foreign key (depot_id) references jardins.depots not valid;

alter table jardins.distributions
  add foreign key (adherent_id) references jardins.adherents not valid;

alter table jardins.distributions
  validate constraint distributions_depot_id_fkey;

alter table jardins.distributions
  add foreign key (jardin_id) references jardins.jardins on update cascade not valid;

alter table jardins.distributions
  validate constraint distributions_jardin_id_fkey;

alter table jardins.distributions
  add foreign key (tournee_id) references jardins.tournees not valid;

alter table jardins.distributions
  validate constraint distributions_tournee_id_fkey;

alter table jardins.distributions
  add constraint adresse_unique check ((depot_id is not null and adherent_id is null) OR (depot_id is null and adherent_id is not null))
