

create table jardins.saisons (
  saison_id bigint not null,
  jardin_id bigint not null,
  saison text,
  date_debut date,
  date_fin date
);

alter table jardins.saisons
  alter column saison_id
  add generated by default as identity;

alter table jardins.saisons
  add primary key (saison_id);

alter table jardins.saisons
  add foreign key (jardin_id) references jardins.jardins on delete cascade;

alter table jardins.saisons enable row level security;

create policy "Lecture publique"
on jardins.saisons
as permissive
for select
to public
using (true);

alter table jardins.cotisations
  add foreign key (saison_id) references jardins.saisons;

-- frequences

create table jardins.frequences (
  frequence_id bigint not null,
  jardin_id bigint,
  frequence text
);

alter table jardins.frequences
  alter column frequence_id
  add generated by default as identity;

alter table jardins.frequences
  add primary key (frequence_id);
