

create table jardins.depots (
  depot_id bigint not null,
  jardin_id bigint not null,
  depot text not null,
  adresse_id bigint,
  contact_id bigint,
  capacite integer default 0
);

alter table jardins.depots
  alter column depot_id
  add generated by default as identity;

alter table jardins.depots
  add primary key (depot_id);

alter table jardins.depots
  add foreign key (jardin_id) references jardins.jardins on delete cascade;

alter table jardins.depots
  add foreign key (adresse_id) references jardins.adresses not valid;

alter table jardins.depots validate constraint depots_adresse_id_fkey;

alter table jardins.depots
  add foreign key (contact_id) references jardins.contacts not valid;

alter table jardins.depots validate constraint depots_contact_id_fkey;

alter table jardins.depots enable row level security;

create policy "Lecture publique"
on jardins.depots
as permissive
for select
to public
using (true);
