

create table jardins.produits (
    produit_id bigint not null,
    jardin_id bigint not null,
    produit text not null,
    prix numeric,
    marge numeric
);

alter table jardins.produits
  alter column produit_id
  add generated by default as identity;

alter table jardins.produits
  add primary key (produit_id);

alter table jardins.produits
  add foreign key (jardin_id) references jardins.jardins;

alter table jardins.produits enable row level security;

create policy "Lecture publique"
on jardins.produits
as permissive
for select
to public
using (true);

-- paniers

create table jardins.paniers (
  panier_id bigint not null,
  produit_id bigint not null,
  panier text not null,
  frequence_id bigint,
  quantite smallint,
  prix numeric
);

alter table jardins.paniers
  alter column panier_id
  add generated by default as identity;

alter table jardins.paniers
  add primary key (panier_id);

alter table jardins.paniers
  add foreign key (produit_id) references jardins.produits;

alter table jardins.paniers
  add foreign key (frequence_id) references jardins.frequences not valid;

alter table jardins.paniers
  validate constraint paniers_frequence_id_fkey;

alter table jardins.paniers enable row level security;

create policy "Lecture publique"
on jardins.paniers
as permissive
for select
to public
using (true);

create table jardins.propositions (
  proposition_id bigint not null,
  frequence_id bigint not null,
  planning_id bigint not null
);

alter table jardins.propositions
  alter column proposition_id
  add generated by default as identity;

alter table jardins.propositions
  add foreign key (frequence_id) references jardins.frequences;
