

create type jardins.etat_livraison as enum (
  'à livrer',
  'livré',
  'non pris',
  'perdu'
);

create table jardins.livraisons (
  livraison_id bigint not null,
  jardin_id bigint not null,
  abonnement_id bigint not null, -- abonnement -> abonne
  distribution_id bigint not null, -- depot
  produit_id bigint not null,
  qte numeric  not null default '1'::numeric,
  livre jardins.etat_livraison not null default  'à livrer',
  planning_id bigint not null -- jour
);

alter table jardins.livraisons
  alter column livraison_id
  add generated by default as identity;

alter table jardins.livraisons
  add primary key (livraison_id);


alter table jardins.livraisons
  add foreign key (jardin_id) references jardins.jardins on delete cascade not valid;

alter table jardins.livraisons
  validate constraint livraisons_jardin_id_fkey;

alter table jardins.livraisons
  add foreign key (abonnement_id) references jardins.abonnements on delete cascade not valid;

alter table jardins.livraisons
  validate constraint livraisons_abonnement_id_fkey;

alter table jardins.livraisons
  add foreign key (distribution_id) references jardins.distributions not valid;

alter table jardins.livraisons
  validate constraint livraisons_distribution_id_fkey;




alter table jardins.livraisons enable row level security;

create policy "Lecture publique"
on jardins.livraisons
as permissive
for select
to public
using (true);
