

create table jardins.fermetures (
  fermeture_id bigint not null,
  jardin_id bigint not null,
  saison_id bigint not null,
  semaine smallint not null
);

alter table jardins.fermetures
  alter column fermeture_id
  add generated by default as identity;

alter table jardins.fermetures
  add primary key (fermeture_id);

alter table jardins.fermetures
  add foreign key (jardin_id) references jardins.jardins on delete cascade;

alter table jardins.fermetures
  add constraint fermeture check (semaine <= 53);

alter table jardins.fermetures enable row level security;

create policy "Lecture publique"
on jardins.fermetures
as permissive
for select
to public
using (true);


-- jours fériés

create table jardins.feries (
  ferie_id bigint not null,
  jardin_id bigint,
  ferie text,
  jour date
);

alter table jardins.feries
  alter column ferie_id
  add generated by default as identity;

alter table jardins.feries
  add primary key (ferie_id);

alter table jardins.feries
  add foreign key (jardin_id) references jardins.jardins on update cascade;

alter table jardins.feries enable row level security;

create policy "Lecture publique"
on jardins.feries
as permissive
for select
to public
using (true);
