

create table jardins.plannings (
  planning_id bigint not null,
  calendrier_id bigint,
  jour date
);

alter table jardins.plannings
  alter column planning_id
  add generated by default as identity;

alter table jardins.plannings
  add foreign key (calendrier_id) references jardins.calendriers;

alter table jardins.plannings
  add primary key (planning_id);

alter table jardins.propositions
  add foreign key (planning_id) references jardins.plannings;
