

-- profils

create table jardins.profils (
  profil_id bigint not null,
  profil text
);

alter table jardins.profils
  alter column profil_id
  add generated by default as identity;

alter table jardins.profils
  add primary key (profil_id);

create table jardins.cotisations (
  cotisation_id bigint not null,
  saison_id bigint,
  profil_id bigint,
  montant numeric
);

alter table jardins.cotisations
  alter column cotisation_id
  add generated by default as identity;

alter table jardins.cotisations
  add primary key (cotisation_id);

alter table jardins.cotisations
  add foreign key (profil_id) references jardins.profils;

create table jardins.adherents (
  adherent_id bigint not null,
  created_at timestamp with time zone default now() not null,
  jardin_id bigint not null,
  adherent text not null,
  profil_id bigint not null,
  depot_id bigint,
  email text,
  date_sortie date,
  adresse_id bigint
);

comment on column jardins.adherents.depot_id is 'Dépôt préféré.';

alter table jardins.adherents
  alter column adherent_id
  add generated by default as identity;

alter table jardins.adherents
  add primary key (adherent_id);

alter table jardins.adherents
  add foreign key (jardin_id) references jardins.jardins;

alter table jardins.adherents
  add foreign key (profil_id) references jardins.profils;

alter table jardins.adherents enable row level security;

create policy "Lecture publique"
on jardins.adherents
as permissive
for select
to public
using (true);


-- adhesions

create table jardins.adhesions (
  adhesion_id bigint not null,
  created_at timestamp with time zone default now() not null,
  adherent_id bigint not null,
  jardin_id bigint not null,
  date_adhesion date,
  montant numeric,
  saison_id bigint not null
);

alter table jardins.adhesions
  alter column adhesion_id
  add generated by default as identity;

alter table jardins.adhesions
  add primary key (adhesion_id);

alter table jardins.adhesions
  add foreign key (adherent_id) references jardins.adherents;

alter table jardins.adhesions
  add foreign key (jardin_id) references jardins.jardins;

alter table jardins.adhesions
  add constraint adhesions_un
  unique (adherent_id,jardin_id,saison_id);

alter table jardins.adhesions enable row level security;

create policy "Lecture publique"
on jardins.adhesions
as permissive
for select
to public
using (true);
