

create table jardins.fournisseurs (
  fournisseur_id bigint not null,
  jardin_id bigint not null,
  fournisseur text,
  tva text,
  adresse_id bigint
);

alter table jardins.fournisseurs
  alter column fournisseur_id
  add generated by default as identity;

alter table jardins.fournisseurs
  add primary key (fournisseur_id);

alter table jardins.fournisseurs
  add foreign key (jardin_id) references jardins.jardins on delete cascade;

alter table jardins.fournisseurs
  add foreign key (adresse_id) references jardins.adresses on delete set null not valid;

alter table jardins.fournisseurs
  validate constraint fournisseurs_adresse_id_fkey;

alter table jardins.fournisseurs enable row level security;

create policy "Lecture publique"
on jardins.fournisseurs
as permissive
for select
to public
using (true);
