


create table jardins.jardins (
  jardin_id bigint not null,
  jardin text,
  adresse_id bigint,
  tva text,
  contact_id bigint
);

alter table jardins.jardins
  alter column jardin_id
  add generated by default as identity;

alter table jardins.jardins
  add primary key (jardin_id);

alter table jardins.jardins enable row level security;

create policy "Lecture publique"
  on jardins.jardins
  as permissive
  for select
  to public
  using (true);

-- adresses

set search_path to public, jardins, extensions;

create table jardins.adresses (
  adresse_id bigint not null,
  jardin_id bigint,
  adresse text,
  codepostal text,
  ville text,
  localisation geometry(point, 4326) default null::geometry
);

alter table jardins.adresses
  alter column adresse_id
  add generated by default as identity;

create index adresses_localisation_idx
  on jardins.adresses
  using gist (localisation);

alter table jardins.adresses
  add primary key (adresse_id);

alter table jardins.adresses
  add foreign key (jardin_id) references jardins.jardins not valid;

alter table jardins.adresses
  validate constraint adresses_jardin_id_fkey;

alter table jardins.jardins
  add foreign key (adresse_id) references jardins.adresses on delete set null not valid;

alter table jardins.jardins
  validate constraint jardins_adresse_id_fkey;


alter table jardins.adresses enable row level security;

create policy "Lecture publique"
on jardins.adresses
as permissive
for select
to public
using (true);


-- contacts

create table jardins.contacts (
  contact_id bigint not null,
  jardin_id bigint,
  contact text,
  telephone text,
  email text
);

alter table jardins.contacts
  alter column contact_id
  add generated by default as identity;

alter table jardins.contacts
  add primary key (contact_id);

alter table jardins.contacts
  add foreign key (jardin_id) references jardins.jardins not valid;

alter table jardins.contacts
  validate constraint contacts_jardin_id_fkey;

alter table jardins.jardins
  add foreign key (contact_id) references jardins.contacts on delete set null not valid;

alter table jardins.jardins
  validate constraint jardins_contact_id_fkey;

alter table jardins.contacts enable row level security;

create policy "Lecture publique"
on jardins.contacts
as permissive
for select
to public
using (true);
